import magnetohydrodynamics_electrohydrodynamics_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace magnetohydrodynamics_electrohydrodynamics_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end magnetohydrodynamics_electrohydrodynamics_theorem_canonical_lane_mathlib
end HautevilleHouse
